apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: networks.samplecrd.k8s.io
  annotations:
    "api-approved.kubernetes.io": "https://github.com/kubernetes/kubernetes/pull/78458"
spec:
  group: samplecrd.k8s.io
  names:
    kind: Network
    plural: networks
    singular: network
    shortNames:
    - nw
  scope: Namespaced
  versions:
  - served: true
    storage: true
    name: v1
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              cidr:
                type: string
              gateway:
                type: string
